# This workflow will build a Go project only when commit messages start with fix:, add:, or feat:
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Conditional execution: Only run the build job if the commit message starts with fix:, add:, or feat:
    if: |
      startsWith(github.event.head_commit.message, 'fix:') ||
      startsWith(github.event.head_commit.message, 'add:') ||
      startsWith(github.event.head_commit.message, 'feat:')
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'  # Specify your Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.tool_cache }}/go-build
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o wrm.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wrm-exe
          path: wrm.exe
